### ISSUE TITLE
Signin and Signup Page

### ISSUE THREAD

**Issue by Harshwardhan08** [arikaki/SE-project#17]
![image](https://user-images.githubusercontent.com/36102833/153038708-5bc7d410-bddd-4105-96bc-11eae19f75a9.png)
![image](https://user-images.githubusercontent.com/36102833/153038780-af4e564f-4737-4759-82d3-81811829891e.png)

Need to create sign in and sign up pages following above design and needs to be added in the application flow.

**Comment by arikaki** [comment]
completed
