### ISSUE TITLE
Fade screen with dark tint when search box focused

### ISSUE THREAD

**Issue by Harshwardhan08** [arikaki/SE-project#44]
![image](https://user-images.githubusercontent.com/36102833/159364710-fabb1fbf-1050-45e0-91dc-03dba4ec89b4.png)
![image](https://user-images.githubusercontent.com/36102833/159364754-982c57e3-4c68-4453-bdc1-c789edda4131.png)

Refer the screenshot for clarity.

**Comment by Nikhil1612** [comment]
done
